server:
  port: 8083

spring:
  application:
    name: spring-boot-3-sso-sample
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
    username: root
    password: 123456

#logging:
#  level:
#    org.springframework.security: trace